version: "3.7"
services:
  mongo:
    image: "mongo:3"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
    volumes:
      - ~/mongo:/data/db
    networks:
      - mongo-compose-network
    ports:
      - ${MONGODB_PORT}

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $(MONGO_EXPRESS_USERNAME)
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMIN_PASSWORD}
    ports:
      - 8081:8081
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

  scrapper:
    image: "edumco/doe-sangue:latest"
    environment:
      MONGODB_SERVER: mongo
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION}
      WAIT_HOSTS: mongo:${MONGODB_PORT}
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

networks:
  mongo-compose-network:
